# -*- coding: utf-8 -*-
"""FlaskPredictiveService.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L_o-Q7EasKdalj0j6gv5sjmPCuYb9KLN
"""

# Import necessary libraries
import pickle
from flask import Flask, request, jsonify

# Initialize Flask application
app = Flask(__name__)

# Load the pre-trained machine learning model
with open('trained_model.pkl', 'rb') as model_file:
    model = pickle.load(model_file)

# Define an API endpoint for model inference
@app.route('/predict', methods=['POST'])
def predict():
    try:
        # Get input data from the request
        data = request.json

        # Perform data preprocessing (ensure it matches preprocessing during training)
        # Example: data preprocessing code here

        # Make predictions using the loaded model
        predictions = model.predict([data])

        # Convert predictions to a response format (e.g., JSON)
        response = {
            'predictions': predictions.tolist()
        }

        return jsonify(response)

    except Exception as e:
        return jsonify({'error': str(e)})

if __name__ == '__main__':
    # Run the Flask application on a specified host and port
    app.run(host='0.0.0.0', port=5000)